### ISSUE TITLE
Arena mode

### ISSUE THREAD

**Issue by gadonng** [yangyuan/hearthrock#35]
Hi,

It would be nice to be able to run a bot on Arena mode, making card selection and play afterwards. 

Do you plan to implement it?

Also is there some of you guys trying to implement a deep learning AI bot with HearthRock?

**Comment by yangyuan** [comment]
Not planning to support arena mode.

----  I AM A BEAUTIFUL SPLIT LINE ----

I actually prefer deep learning, but it is a supervised learning method.
Which means, we need training data. However, I don't have a good training data.

----  I AM AN ANOTHER BEAUTIFUL SPLIT LINE ----

What I am trying to do is card2vector or spell2vector. (I prefer spell2vector so that I don't need to re-train after they update the cards.)

If I can finish spell2vector, it might contribute to many supervised learning methods, as well as traditional AI technologies such as min-max trees.
