### ISSUE TITLE
Unbuildable on macOS

### ISSUE THREAD

**Issue by elbowdonkey** [yangyuan/hearthrock#49]
Hearthrock.Client and Hearthrock.Tests show a warning of "This project type not supported" in Visual Studio Community 2017 for Mac.

Are there dependencies on macOS that I should know about?

**Comment by AiSatan** [comment]
Hi,

I'm not sure, I never use macOS, but

https://stackoverflow.com/questions/31864724/can-you-install-net-framework-on-mac

I think, on Mac and Linux you can only use net core, but the client app using full .net framework 

It's good idea to check: can we build all with only  net core, because right now, I think you can't 

If you want patched version of lib, I think you can go to second issue here, about battlecry and try to use from the last comment from me, I think Mac use same lib for hs
If not, don't forget make some backups or just scan/repair the game with battle.net app

**Comment by elbowdonkey** [comment]
I Invested a bit further.

Everything except for Hearthrock.Client and Hearthrock.Tests builds.

I'm not very familiar with the .NET ecosystem, so can't quite see what's wrong. My guess is that the client won't build because it's using System.Xaml (or it's a WPF app? both are new to me, so I have no idea).

I tried using the recommended Portable.Xaml package which seems like it should provide cross platform compatibility with System.Xaml, but the build still fails for reasons I can't quite narrow down yet. I might try using the same package but build it in Windows to see if it can produce a macOS build.

**Comment by AiSatan** [comment]
I think, you can build project as net core, without ui as console
You just need separate ui from important code and add it to new net core project
But I'm not sure how it'll be work on macos

I think you can find something like manual to migrate to net core

**Comment by yangyuan** [comment]
Right now this project doesn't support Mac version.

The code is pure .NET code which can be built on any platform. However, the NuGet package is built on windows Hearthstone binaries (which won't work on Mac).

It is possible to make this project to support Mac, but it will be a problem to maintain it.
