### ISSUE TITLE
Everytime the bot hits a discover card the service returns 0 PlayOptions.

### ISSUE THREAD

**Issue by yangyuan** [yangyuan/hearthrock#9]
A user reported issue.
Need investigating.

**Comment by AiSatan** [comment]
I am not sure, but I tried to play as jade druid and everything works fine, jade idols, wrath and other have the play options.
Can you please test it as well, maybe I miss something and can fix

**Comment by arthursouza** [comment]
Still facing this issue, @AiSatan you mentioned playing jade idols, wrath and others, but the choose one mechanic seem to be working properly, for some reason **discover** is returning no PlayOptions.

**Comment by lanhin** [comment]
@arthursouza Sorry I'm new to the repo and C#. What do you mean by "class ChoiceCardMgr"? I just can't find it from the source. Not only discover card, I found some battlecry cards has similar problem. I wonder if I can get more card info in scene, like whether it's a discover card (so that I can do some track in the action list). @yangyuan Is class Entity has a method for that? Or how can I get all the member functions of Entity? That turns out to be a problem to me at present. 

Any advice will be appreciated. Thanks!

**Comment by AiSatan** [comment]
![image](https://user-images.githubusercontent.com/2905049/36041405-77864cda-0dd9-11e8-9fd5-861405db5c3a.png)
it's in the HS assembly (Assembly-CSharp.dll), I will look it later.

I also found a way to debug HS. 


I am using [dnSpy](https://github.com/0xd4d/dnSpy/releases) with [the manual](https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games)

For HS: mono version x32 - v5.6.2

You should download: 
Unity-debugging-win32.zip and dnSpy.zip

Replace Hearthstone_Data\Mono\mono.dll with ~\5.6.2\mono.dll

Run HS

In the dnSpy click Debug - Start Debug - Unity(connect)

ip 127.0.0.1
port 55555

And File - Open - ~\Hearthstone_Data\Managed\Assembly-CSharp.dll

and now, you can set breakpoint anywhere

**Comment by AiSatan** [comment]
Well, I think I can fix discover and adapt, it's work for me now, but I need more test and I am not sure how to implement it better

**Comment by yangyuan** [comment]
**About Choice Cards**

The suboptions are available. But sometimes bot might be stuck in a state that:

>  The parent card has been chosen and the sub cards cannot be chosen. And the bot is trying to choose other cards instead of sub cards.

This might happen due to some client/human issues. Right now I don't think its an issue.

**About Discover/Adapt Cards**

IDK why, but in the code Blizzard choose to make Discover/Adapt not an "Option", instead, they make it a separated field "Choices" in GameState class. I didn't notice that.

Maybe because the behavior of Discover/Adapt and Mulligan are too similar so they decided to share the design.

I've changed the code and doing some final test, probably will push the commit soon.

But, I'm assuming all the Discover/Adapt cards will only ask for choosing one option, is there any exceptions?

**ChoiceCardMgr**

I don't think this is a good direction. ChoiceCardMgr is a UI class. I believe Blizzard must be following the basic design practices and keep "State" and "UI" separated. ChoiceCardMgr probably has all the information we need but they might change that frequently.

**Comment by yangyuan** [comment]
#43

**Comment by AiSatan** [comment]
![image](https://user-images.githubusercontent.com/2905049/36095388-14e3afb0-1003-11e8-9a52-b0d134223b57.png)

I still have a problem with battlecry, it's work sometime, but not always, it's juct stack in this state, and try to play another card, but can't.

Scene tell me - card on the table;


> ChoiceCardMgr

I think about another implementation,  state.GetFriendlyEntityChoices().Entities has cards for choose and we can return it like "/choise" for bot brain, instead of checking scene.Self.Choices every time

![image](https://user-images.githubusercontent.com/2905049/36095579-cbac93d8-1003-11e8-9387-c67377a88d99.png)

**Comment by yangyuan** [comment]
@AiSatan 
I decide to add `Choices` to `RockPlayer` because I want to use the same design as Blizzard does.

For the problem you mentioned, is not related to `Choices`.
Theoretically, it can only happen when you start the bot after you played a card with Battlecry which needs an operation. Is that the case?
If it's not, we can create another issue for that.

**Comment by lanhin** [comment]
@AiSatan Thanks for sharing your info. That will be very helpful.
I'm on a break these days. I'll try the new version soon. @yangyuan

**Comment by lanhin** [comment]
@AiSatan For the battlecry problem. I also met it. I thought we may solve it by the bot side. That is, when we decide to play `[num1, num2]`, which num1 is a card id with minion type and num2 is a minion id, then we change it into `[num1], [num1, num2]`, which means we play `num1` first and then use it to attack `num2`.

It's just an idea, I haven't implemented it.
